# Generated by Django 2.2.6 on 2020-02-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200127_1330'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
