# Generated by Django 2.2.6 on 2020-02-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birthday',
            new_name='date_of_birth',
        ),
    ]
